### ISSUE TITLE
License please?

### ISSUE THREAD

**Issue by dalb8** [abodehq/MP3QuranForAndriod#1]
Many apps on Github are free software , meaning they can be distributed freely according to the license they provide. F-Droid.org is a repository for free software on Android; we would like to distribute this app if it has a free licence such as GPL , Apache or any of the accepted licences on this page http://www.gnu.org/licenses/licenses.html. If  you decide to make it free please put a file called COPYING in the root of the repo stating how you wish to allow people to copy the code. Also could you provide references for the jars in libs/ . Thanks.

**Comment by abodehq** [comment]
My App is build to be used only for Quran MP3 Applications for free. 
Sorry for this but this application aim to spread the beauty of The Holy Quran.

Sorry Again.

**Comment by dalb8** [comment]
So this app is only a demonstration? I don't understand why you think that distributing the app via Google Play is better than distributing via F-Droid. You reach more people via Google but they distribute apps just so they can spy on their users; we do it for free and people can download directly from a website. 

Even so, if you want other apps to be able to re-use the code you should apply a licence; if not, state clearly that "all rights are reserved". In other words, tell people that they are allowed copy.
